geomanager/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenRefreshView, )

from geomanager.viewsets.aoi import AoiViewSet
from .views import (
    RasterTileView,
    VectorTileView,
    map_view,
    RegisterView,
    ResetPasswordView,
    tile_gl,
    tile_json_gl,
    style_json_gl,
    get_mapviewer_config,
    GeoJSONPgTableView, AdditionalBoundaryVectorTileView, get_boundary_data_feature_by_id
)
from .views.auth import (
    EmailTokenObtainPairView,
    UserTokenVerifyView
)
from .views.profile import (
    get_geomanager_user_profile,
    create_or_update_geomanager_user_profile
)
from .views.raster_file import (
    RasterDataPixelView,
    RasterDataPixelTimeseriesView,
    RasterDataGeostoreView,
    RasterDataGeostoreTimeseriesView, raster_file_as_tile_json, RasterThumbnailView
)
from .viewsets import (
    RasterLayerRasterFileDetailViewSet,
    VectorTableFileDetailViewSet,
    DatasetViewSet,
    GeostoreViewSet,
    AdminBoundaryViewSet,
    MetadataViewSet
)

router = SimpleRouter(trailing_slash=True)

router.register(r'api/datasets', DatasetViewSet, basename="datasets")
router.register(r'api/metadata', MetadataViewSet, basename="metadata")

router.register(r'api/file-raster', RasterLayerRasterFileDetailViewSet, basename="file-raster")
router.register(r'api/vector-data', VectorTableFileDetailViewSet, basename="vector-data")

router.register(r'api/aoi', AoiViewSet, basename="aoi")

urlpatterns = [
                  # MapViewer
                  path(r'mapviewer/', map_view, name="mapview"),
                  path(r'mapviewer/<str:location_type>/', map_view, name="mapview"),
                  path(r'mapviewer/<str:location_type>/<str:adm0>/', map_view, name="mapview"),
                  path(r'mapviewer/<str:location_type>/<str:adm0>/<str:adm1>/', map_view, name="mapview"),
                  path(r'mapviewer/<str:location_type>/<str:adm0>/<str:adm1>/', map_view, name="mapview"),
                  path(r'mapviewer/<str:location_type>/<str:adm0>/<str:adm1>/<str:adm2>/', map_view, name="mapview"),

                  # MapViewer configuration
                  path(r'api/mapviewer-config', get_mapviewer_config, name="mapview_config"),

                  # Authentication
                  path('api/auth/register/', RegisterView.as_view(), name='auth_register'),
                  path('api/auth/reset-password/', ResetPasswordView.as_view(), name='auth_password_reset'),
                  path('api/auth/token/', EmailTokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/auth/token/verify/', UserTokenVerifyView.as_view(), name='token_verify'),
                  path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

                  # User Profile
                  path('api/geomanager-profile/<int:user_id>', get_geomanager_user_profile,
                       name='get_geomanager_user_profile'),
                  path('api/geomanager-profile/update/<str:user_id>', create_or_update_geomanager_user_profile,
                       name='update_geomanager_user_profile'),

                  # # User Areas of Interest
                  # path('api/aoi/<int:user_id>', get_user_aoi_list, name='get_user_aoi_list'),
                  # path('api/aoi/', create_aoi, name='create_user_aoi'),
                  # path('api/aoi/', create_aoi, name='create_user_aoi'),

                  # Country
                  path(r'api/country', AdminBoundaryViewSet.as_view({"get": "get"}), name="country_list"),
                  path(r'api/country/<str:gid_0>', AdminBoundaryViewSet.as_view({"get": "get_regions"}),
                       name="country_regions"),
                  path(r'api/country/<str:gid_0>/<str:gid_1>',
                       AdminBoundaryViewSet.as_view({"get": "get_sub_regions"}),
                       name="country_sub_regions"),

                  # Geostore
                  path(r'api/geostore/', GeostoreViewSet.as_view({"post": "post"}), name="geostore"),
                  path(r'api/geostore/<uuid:geostore_id>', GeostoreViewSet.as_view({"get": "get"}),
                       name="get_by_geostore"),
                  path(r'api/geostore/admin/<str:gid_0>', GeostoreViewSet.as_view({"get": "get_by_admin"}),
                       name="get_by_gid0"),
                  path(r'api/geostore/admin/<str:gid_0>/<str:gid_1>', GeostoreViewSet.as_view({"get": "get_by_admin"}),
                       name="get_by_gid1"),
                  path(r'api/geostore/admin/<str:gid_0>/<str:gid_1>/<str:gid_2>',
                       GeostoreViewSet.as_view({"get": "get_by_admin"}),
                       name="get_by_gid2"),

                  # Boundary feature by id
                  path(r'api/map-boundary-data/<str:table_name>/<int:gid>',
                       get_boundary_data_feature_by_id, name="boundary_data_feature_by_id"),

                  # Tile JSON
                  path(r'api/raster/<uuid:layer_id>/tiles.json', raster_file_as_tile_json,
                       name="raster_file_tile_json"),

                  # Tiles
                  path(r'api/raster-tiles/<uuid:layer_id>/<int:z>/<int:x>/<int:y>', RasterTileView.as_view(),
                       name="raster_tiles"),
                  path(r'api/vector-tiles/<int:z>/<int:x>/<int:y>', VectorTileView.as_view(), name="vector_tiles"),
                  path(r'api/map-boundary-tiles/<str:table_name>/<int:z>/<int:x>/<int:y>',
                       AdditionalBoundaryVectorTileView.as_view(),
                       name="map_boundary_tiles"),

                  # Thumbnail
                  path(r'api/raster-file-thumbnail/<int:file_id>.png', RasterThumbnailView.as_view(),
                       name="raster_file_thumbnail"),

                  # Data
                  path(r'api/raster-data/pixel/<uuid:layer_id>', RasterDataPixelView.as_view(),
                       name="raster_data_pixel"),
                  path(r'api/raster-data/pixel/timeseries/<uuid:layer_id>', RasterDataPixelTimeseriesView.as_view(),
                       name="raster_data_pixel_timeseries"),

                  path(r'api/raster-data/geostore/<uuid:layer_id>', RasterDataGeostoreView.as_view(),
                       name="raster_data_geostore"),
                  path(r'api/raster-data/geostore/timeseries/<uuid:layer_id>',
                       RasterDataGeostoreTimeseriesView.as_view(),
                       name="raster_data_geostore_timeseries"),

                  # FeatureServ
                  path(r'api/feature-serv/<str:table_name>.geojson', GeoJSONPgTableView.as_view(), name="feature_serv"),

                  # Tiles GL
                  path(r'api/tile-gl/tile/<str:source_slug>/<int:z>/<int:x>/<int:y>.pbf', tile_gl, name="tile_gl"),
                  path(r'api/tile-gl/tile-json/<str:source_slug>.json', tile_json_gl, name="tile_json_gl"),
                  path(r'api/tile-gl/style/<str:source_slug>.json', style_json_gl, name="style_json_gl"),

                  # Additional, standalone URLs from django-large-image
                  path('', include('django_large_image.urls')),
                  path('', include('adminboundarymanager.urls')),
              ] + router.urls

home/urls.py
from django.urls import path

from .views import StationsTileView

urlpatterns = [
    path(r'api/station-tiles/<int:z>/<int:x>/<int:y>', StationsTileView.as_view(), name="station_tiles"),
]

sandbox/home/urls.py
from django.urls import path

from .views import StationsTileView

urlpatterns = [
    path(r'api/station-tiles/<int:z>/<int:x>/<int:y>', StationsTileView.as_view(), name="station_tiles"),
]

home/models.py
from django.contrib.gis.db import models
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from django_tables2 import tables, LazyPaginator, TemplateColumn
from wagtail.admin.panels import FieldPanel
from wagtail.api.v2.utils import get_full_url
from wagtail.contrib.routable_page.models import path, RoutablePageMixin
from wagtail.contrib.settings.models import BaseSiteSetting
from wagtail.contrib.settings.registry import register_setting
from wagtail.models import Page
from wagtailcache.cache import cache_page

from geomanager.fields import ListField
from geomanager.models import SubCategory, Metadata
from geomanager.utils.vector_utils import get_model_field


@method_decorator(cache_page, name="serve")
class HomePage(Page):
    pass


@register_setting
class StationSettings(BaseSiteSetting):
    stations_table_name = "home_station"
    db_schema = "public"

    columns = models.JSONField(blank=True, null=True)
    geom_type = models.CharField(max_length=100, blank=True, null=True)
    bounds = ListField(max_length=256, blank=True, null=True)
    name_column = models.CharField(max_length=100, blank=True, null=True)

    show_on_mapviewer = models.BooleanField(default=False, verbose_name=_("Show on Mapviewer"),
                                            help_text=_("Check to show stations data on Mapviewer"))
    layer_title = models.CharField(max_length=100, blank=True, null=True, default="Stations",
                                   verbose_name=_("Stations Layer Title"))
    geomanager_subcategory = models.ForeignKey(SubCategory, null=True, blank=True,
                                               verbose_name=_("Stations Layer SubCategory"),
                                               on_delete=models.SET_NULL)
    geomanager_layer_metadata = models.ForeignKey(Metadata, on_delete=models.SET_NULL, blank=True, null=True,
                                                  verbose_name=_("Stations Layer Metadata"))

    panels = [
        FieldPanel("show_on_mapviewer"),
        FieldPanel("layer_title"),
        FieldPanel("geomanager_subcategory"),
        FieldPanel("geomanager_layer_metadata"),
    ]

    @cached_property
    def full_table_name(self):
        return f"{self.db_schema}.{self.stations_table_name}"

    @cached_property
    def stations_vector_tiles_url(self):
        base_url = reverse("station_tiles", args=(0, 0, 0)).replace("/0/0/0", r"/{z}/{x}/{y}")
        return base_url

    def get_station_model(self):
        fields = self.station_fields_factory()

        attrs = {
            **fields,
            "managed": False,
            "__module__": "home"
        }

        station_model = type("Station", (models.Model,), attrs)

        return station_model

    def station_fields_factory(self):
        geom_type = self.geom_type or "Point"
        fields = {
            "geom": get_model_field(geom_type)()
        }

        if isinstance(self.columns, list):
            for column in self.columns:
                data_type = column.get("data_type")
                name = column.get("name")
                label = column.get("label") or name
                if data_type:
                    model_field = get_model_field(column.get("data_type"))

                    if model_field:
                        field_kwargs = {"verbose_name": label}
                        if name == "gid":
                            field_kwargs.update({"primary_key": True})
                        fields.update({name: model_field(**field_kwargs)})

        return fields

    @cached_property
    def station_columns_list(self):
        station_columns = []
        if self.columns and isinstance(self.columns, list):
            for column in self.columns:
                name = column.get("name")
                if name:
                    station_columns.append(name)
        return station_columns

    @cached_property
    def station_table_columns_list(self):
        table_columns = []
        if self.columns and isinstance(self.columns, list):
            for column in self.columns:
                name = column.get("name")
                label = column.get("label")
                table = column.get("table")
                if name and table:
                    table_columns.append({"name": name, "label": label})
        return table_columns

    @cached_property
    def station_popup_columns_list(self):
        popup_columns = []
        if self.columns and isinstance(self.columns, list):
            for column in self.columns:
                name = column.get("name")
                label = column.get("label")
                popup = column.get("popup")
                if name and popup:
                    popup_columns.append({"name": name, "label": label})
        return popup_columns


class StationsPage(RoutablePageMixin, Page):
    template = "stations/stations_list_page.html"
    parent_page_types = ["home.HomePage"]
    subpage_types = []
    max_count = 1

    content_panels = Page.content_panels

    @path('')
    def all_stations(self, request, *args, **kwargs):
        context = {}
        station_settings = StationSettings.for_request(request)

        stations_vector_tiles_url = get_full_url(request, station_settings.stations_vector_tiles_url)

        context.update({
            "mapConfig": {
                "stationBounds": station_settings.bounds or [],
                "stationsVectorTilesUrl": stations_vector_tiles_url,
            },
        })

        # get stations model
        station_model = station_settings.get_station_model()

        # get all columns
        station_table_columns_list = station_settings.station_table_columns_list

        table_fields = [field.get("name") for field in station_table_columns_list]

        page_url = get_full_url(request, self.url)

        class StationTable(tables.Table):
            detail_url = TemplateColumn('<a href="" target="_blank"></a>')

            class Meta:
                model = station_model
                fields = table_fields

            def render_detail_url(self, value, record):
                record_pk_suffix = str(record.gid)
                if page_url and not page_url.endswith("/"):
                    record_pk_suffix = f"/{record_pk_suffix}"
                url = page_url + record_pk_suffix
                return format_html(
                    "<a href='{}'>View detail</a>",
                    url
                )

        stations_table = StationTable(station_model.objects.all())

        try:
            stations_table.paginate(page=request.GET.get("page", 1), per_page=50, paginator_class=LazyPaginator)
        except Exception as e:
            stations_table = None

        context.update({
            "stations_table": stations_table,
            "popup_fields": station_settings.station_popup_columns_list
        })

        return self.render(request, context_overrides={**context})

    @path('<int:station_pk>/')
    def station_detail(self, request, station_pk):
        station_settings = StationSettings.for_request(request)

        # get stations model
        station_model = station_settings.get_station_model()

        station = station_model.objects.filter(pk=station_pk)

        if station.exists:
            station = station.first()
        else:
            station = None

        context = {
            "station": station,
            "columns": station_settings.columns,
            "bounds": station_settings.bounds,
            "station_name_column": station_settings.name_column
        }

        return self.render(request, template="stations/station_detail_page.html", context_overrides=context)

home/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class StationsUploadForm(forms.Form):
    shp_zip = forms.FileField(required=True, label=_("Stations Shapefile ZIP"),
                              widget=forms.FileInput(attrs={'accept': '.zip'}))


class StationColumnsForm(forms.Form):
    columns = forms.JSONField(required=False, widget=forms.HiddenInput)
    name_column = forms.ChoiceField(required=False, label=_("Station name field"))

    def __init__(self, *args, **kwargs):
        column_choices = None
        if "column_choices" in kwargs:
            column_choices = kwargs.get("column_choices")
            kwargs.pop("column_choices")

        super().__init__(*args, **kwargs)

        if column_choices:
            choices = [("", "--------")]
            choices.extend(column_choices)
            self.fields['name_column'].choices = choices
        else:
            self.fields['name_column'].widget = forms.HiddenInput()

sandbox/home/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class StationsUploadForm(forms.Form):
    shp_zip = forms.FileField(required=True, label=_("Stations Shapefile ZIP"),
                              widget=forms.FileInput(attrs={'accept': '.zip'}))


class StationColumnsForm(forms.Form):
    columns = forms.JSONField(required=False, widget=forms.HiddenInput)
    name_column = forms.ChoiceField(required=False, label=_("Station name field"))

    def __init__(self, *args, **kwargs):
        column_choices = None
        if "column_choices" in kwargs:
            column_choices = kwargs.get("column_choices")
            kwargs.pop("column_choices")

        super().__init__(*args, **kwargs)

        if column_choices:
            choices = [("", "--------")]
            choices.extend(column_choices)
            self.fields['name_column'].choices = choices
        else:
            self.fields['name_column'].widget = forms.HiddenInput()

sandbox/home/templates/stations/stations_preview.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load l10n %}
{% load wagtailadmin_tags wagtailimages_tags static %}
{% block titletag %}
    {% blocktranslate trimmed with title=page.get_admin_display_title %}
        Stations Data {{ title }}
    {% endblocktranslate %}
{% endblock %}
{% block extra_css %}
    {{ block.super }}
    <link href="https://unpkg.com/maplibre-gl@3.1.0/dist/maplibre-gl.css" rel="stylesheet"/>
    <link href="{% static "stations/css/stations_preview.css" %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
    {% translate "Stations Data" as header_str %}
    {% translate "Load Stations" as action_text_trans %}

    {% include "wagtailadmin/shared/header.html" with title=header_str icon="map" action_url=load_stations_url action_text=action_text_trans %}

    <div class="nice-padding">
        {% if station_columns %}
            <div style="margin-top: 40px;">
                <div id="preview-map" style="height: 600px;width: 100%"></div>
            </div>
            <div style="margin-top: 20px;">
                <h2 class="title">
                    {% translate "Data Fields" %}
                </h2>
                <table class="listing">
                    <thead>
                    <tr>
                        <th style="font-weight: 700">
                            {% translate "Field" %}
                        </th>
                        <th style="font-weight: 700">
                            {% translate "Label" %}
                        </th>
                        <th style="font-weight: 700">
                            {% translate "Show in Table" %}
                        </th>
                        <th style="font-weight: 700">
                            {% translate "Show in Map Popup" %}
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for column in station_columns %}
                        <tr>
                            <td>{{ column.name }}</td>
                            <td>
                                <input class="station_input" style="max-width: 300px;" type="text"
                                       name="{{ column.name }}_label"
                                       data-column="{{ column.name }}"
                                       data-updatetype="label"
                                       value="{{ column.label }}"
                                       id="{{ column.name }}_label">
                            </td>
                            <td>
                                <input class="station_input" type="checkbox" name="{{ column.name }}_popup"
                                       id="{{ column.name }}_table" data-column="{{ column.name }}"
                                        {% if column.table %} checked{% endif %}
                                       data-updatetype="table">
                            </td>
                            <td>
                                <input class="station_input" type="checkbox" name="{{ column.name }}_popup"
                                       id="{{ column.name }}_popup" data-column="{{ column.name }}"
                                        {% if column.popup %} checked{% endif %}
                                       data-updatetype="popup">
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <form action="{% url 'preview_stations' %}" method="POST"
                      enctype="multipart/form-data">
                    {% if form.non_field_errors %}
                        <div class="non-field_errors" style="margin-bottom: 20px">
                            {% include "wagtailadmin/shared/non_field_errors.html" with form=form %}
                        </div>
                    {% endif %}
                    <ul class="fields">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.is_hidden %}
                                {{ field }}
                            {% else %}
                                {% include "wagtailadmin/shared/field_as_li.html" %}
                            {% endif %}
                        {% endfor %}
                        <li>
                            <button type="submit" class="button">
                                {% translate 'Save' %}
                            </button>
                        </li>
                    </ul>
                </form>
            </div>
            </div>
        {% else %}

            <div class="help-block help-info">
                <svg class="icon icon-help icon" aria-hidden="true">
                    <use href="#icon-help"></use>
                </svg>
                <p>
                    {% translate "No station data loaded." %}
                    {% translate "Please " %}
                    <a href="{{ load_stations_url }}">
                        {% translate "load station data" %}
                    </a>
                    {% translate "to preview" %}
                </p>

            </div>
        {% endif %}
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% if station_columns %}
        <script src="https://unpkg.com/maplibre-gl@3.1.0/dist/maplibre-gl.js"></script>
        <script>

            const mapConfigObj = {{ mapConfig | safe }};
            const {stationBounds, stationsVectorTilesUrl} = mapConfigObj

            const bounds = [[stationBounds[0], stationBounds[1]], [stationBounds[2], stationBounds[3]]]

            const defaultStyle = {
                'version': 8,
                'sources': {
                    'carto-dark': {
                        'type': 'raster',
                        'tiles': [
                            "https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png",
                            "https://b.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png",
                            "https://c.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png",
                            "https://d.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png"
                        ]
                    },
                    'carto-light': {
                        'type': 'raster',
                        'tiles': [
                            "https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png",
                            "https://b.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png",
                            "https://c.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png",
                            "https://d.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png"
                        ]
                    },
                    'wikimedia': {
                        'type': 'raster',
                        'tiles': [
                            "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png"
                        ]
                    }
                },
                'layers': [{
                    'id': 'carto-light-layer',
                    'source': 'carto-light',
                    'type': 'raster',
                    'minzoom': 0,
                    'maxzoom': 22
                }]
            }


            $(document).ready(async function () {
                const $columnsInput = $("#id_columns")

                const map = new maplibregl.Map({
                    container: "preview-map",
                    style: defaultStyle,
                    doubleClickZoom: false,
                });

                await new Promise((resolve) => map.on("load", resolve));

                if (bounds) {
                    map.fitBounds(bounds, {padding: 20})
                }


                // add source
                map.addSource("stations-source", {
                        type: "vector",
                        tiles: [stationsVectorTilesUrl],
                    }
                )

                // add layer
                map.addLayer({
                    'id': 'stations-circle',
                    'type': 'circle',
                    'source': 'stations-source',
                    "source-layer": "default",
                    'paint': {
                        'circle-color': "red",
                        'circle-radius': 10,
                    }
                });


                const $stationLabelInput = $(".station_input")

                $stationLabelInput.on("change", function () {
                    const $this = $(this)
                    const inputType = $this.attr('type')

                    const columnName = $this.data("column")
                    const updateType = $this.data("updatetype")

                    if (columnName && updateType) {
                        let inputValue = $this.val()

                        if (inputType === "checkbox") {
                            inputValue = $this.is(':checked')
                        }
                        updateColumnsData(columnName, updateType, inputValue)
                    }
                })

                const getColumnsData = () => {
                    let columnsData = $columnsInput.val()

                    if (columnsData) {
                        columnsData = JSON.parse(columnsData)

                        return columnsData
                    }

                    return []
                }

                const getPopupFields = () => {
                    const allFields = getColumnsData()
                    return allFields.filter(c => c && c.popup)
                }

                const updateColumnsData = (columnName, updateType, value) => {
                    let columnsData = getColumnsData()


                    columnsData = columnsData.reduce((all, item) => {
                        if (item.name && item.name === columnName) {
                            item[updateType] = value
                        }

                        all.push(item)

                        return all
                    }, [])

                    if (columnsData) {
                        $columnsInput.val(JSON.stringify(columnsData))
                    }
                }

                function featureHtml(f) {
                    const p = f.properties;
                    const popupFields = getPopupFields()


                    const popupProps = Object.keys(p).reduce((all, key) => {
                        if (popupFields.find(f => f.name === key)) {
                            all[key] = p[key]
                        }
                        return all
                    }, {})

                    if (popupProps && !!Object.keys(popupProps).length) {
                        let h = "<div class='station-popup-content'>";
                        for (let k in popupProps) {
                            const column = popupFields.find(f => f.name === k)
                            h += "<p><b>" + `${column.label ? column.label : k}` + ":</b> " + popupProps[k] + "<br/></p>"
                        }
                        h += "</div>";
                        return h
                    }

                    return null
                }


                map.on('click', "stations-circle", function (e) {
                    const popContent = featureHtml(e.features[0])
                    if (popContent) {
                        new maplibregl.Popup()
                            .setLngLat(e.lngLat)
                            .setHTML(popContent)
                            .addTo(map);
                    }
                });


            })

        </script>
    {% endif %}
{% endblock %}

sandbox/home/templates/stations/stations_upload.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load l10n %}
{% load wagtailadmin_tags wagtailimages_tags static %}
{% block titletag %}
    {% blocktranslate trimmed with title=page.get_admin_display_title %}
        Stations Loader {{ title }}
    {% endblocktranslate %}
{% endblock %}

{% block extra_css %}
    {{ block.super }}

    {{ form_media.css }}
{% endblock %}

{% block content %}
    {% trans "Stations Loader" as header_str %}

    {% include "wagtailadmin/shared/header.html" with title=header_str icon="upload" %}

    <div class="nice-padding">
        <div style="margin-top: 40px;"
             id="upload_form_wrapper">
            <form action="{% url 'load_stations' %}" method="POST"
                  enctype="multipart/form-data">
                {% if form.non_field_errors %}
                    <div class="non-field_errors" style="margin-bottom: 20px">
                        {% include "wagtailadmin/shared/non_field_errors.html" with form=form %}
                    </div>
                {% endif %}
                <ul class="fields">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.is_hidden %}
                            {{ field }}
                        {% else %}
                            {% include "wagtailadmin/shared/field_as_li.html" %}
                        {% endif %}
                    {% endfor %}
                    <li>
                        <button type="submit" class="button">
                            {% translate "Upload" %}
                        </button>
                    </li>
                </ul>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {{ form_media.js }}
{% endblock %}